version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    environment: # 環境變數
      POSTGRES_USER: example_user 
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: memory_agent
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d # 初始化腳本會在容器啟動時自動執行
      - postgres_data:/var/lib/postgresql/data # 使用 `postgres_data` 卷來持久化數據
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: